client:
  protocol: http://
  ip: "127.0.0.1"
  api:
    chat: "/chat"
  minimum_port: 12000
  maximum_port: 13000
messages:
  id_message_regex_format: "^id \\d+$"
server:
  protocol: "http://"
  ip: "127.0.0.1"
  port: 12000
  api:
    list: "/list"
    heartbeat: "/heartbeat"